// French messages, rules and examples for seo-page-check.js. Load this file before the engine.
(function(){
const pl=(n,one,many)=>n+' '+(n>1?many:one);
const dec=(x,d)=>x.toFixed(d).replace('.',',');
const thousands=n=>n.toLocaleString('fr-FR');

const msgs={
  g:{kp:'Requête cible',title:'Titre SEO',desc:'Méta description',slug:'URL',video:'Vidéo',vtrans:'Transcription',body:'Contenu',image:'Image mise en avant',tags:'Étiquettes / mots-clés',tech:'Balises de la page (source)'},
  label:{good:'Bon',ok:'Moyen',bad:'Mauvais'},
  overall:p=>p+' / 100 au total',
  counts:n=>[pl(n.good,'bon','bons'),pl(n.ok,'moyen','moyens'),n.bad+' mauvais'],
  kpNone:'Aucune requête cible : le placement des mots-clés n’est pas vérifié.',
  kpLong:n=>'La requête contient '+n+' mots significatifs. De deux à quatre mots, elle est plus facile à positionner.',
  kpOk:n=>'Requête cible définie ('+pl(n,'mot significatif','mots significatifs')+').',
  titleNone:'Ajoutez un titre SEO.',
  titleLong:(w,max)=>'Trop long : environ '+w+' px. Google coupe les titres vers '+max+' px.',
  titleShort:n=>'Court : '+pl(n,'caractère','caractères')+'. Un titre de 30 à 60 caractères exploite mieux l’espace.',
  titleNear:(w,max)=>'Proche de la limite : environ '+w+' px sur '+max+' px.',
  titleGood:(n,w)=>'Bonne longueur : '+pl(n,'caractère','caractères')+', environ '+w+' px.',
  kpStart:'Commence par la requête cible.',
  kpNotStart:'Contient la requête cible, mais pas au début.',
  kpMissing:'Ne contient pas la requête cible.',
  kpIn:'Contient la requête cible.',
  descNone:'Ajoutez une méta description. Sans elle, Google choisit lui-même un extrait de la page.',
  descGood:n=>'Bonne longueur : '+pl(n,'caractère','caractères')+'.',
  descShortish:n=>'Un peu courte : '+pl(n,'caractère','caractères')+'. Visez 120 à 158.',
  descCut:n=>'Risque d’être coupée : '+pl(n,'caractère','caractères')+'. Visez 120 à 158.',
  descShort:n=>'Trop courte : '+pl(n,'caractère','caractères')+'. Visez 120 à 158.',
  descLong:n=>'Trop longue : '+pl(n,'caractère','caractères')+'. Google la coupera après environ 158.',
  slugNone:'Ajoutez l’URL (slug) pour la vérifier.',
  slugChars:'Utilisez uniquement des minuscules, des chiffres et des tirets (pas d’espaces, de majuscules, d’accents ni de tirets bas).',
  slugClean:'Les caractères sont corrects.',
  slugLong:n=>'Le dernier segment est long ('+pl(n,'caractère','caractères')+'). Une URL courte se partage plus facilement.',
  slugKp:'Contient les mots de la requête cible.',
  slugNoKp:'Ne contient pas tous les mots significatifs de la requête cible.',
  slugStop:l=>'L’URL contient des mots vides ('+l+'). Vous pouvez les retirer pour la raccourcir.',
  typo:'Typographie : mettez une espace avant « : », « ; », « ! » et « ? », et à l’intérieur des guillemets « ».',
  vUrlNone:'Ajoutez l’adresse YouTube ou Vimeo, ou le code d’intégration.',
  vUrlNoId:p=>'Aucun identifiant de vidéo trouvé dans cette adresse '+p+'.',
  vUrlOther:'Seules les adresses YouTube et Vimeo sont reconnues.',
  vUrlOk:(p,id)=>'Vidéo '+p+' '+id+' reconnue.',
  vTitleNone:'Ajoutez un titre de vidéo. Il devient le nom (name) dans les données structurées.',
  vTitleMax:n=>'Le titre de la vidéo fait '+pl(n,'caractère','caractères')+'. YouTube en accepte 100.',
  vTitleLong:n=>'Le titre de la vidéo fait '+pl(n,'caractère','caractères')+'. Les résultats vidéo coupent les titres vers 70.',
  vTitleGood:n=>'Bonne longueur du titre de la vidéo : '+pl(n,'caractère','caractères')+'.',
  vTitleKp:'Le titre de la vidéo contient la requête cible.',
  vTitleNoKp:'Le titre de la vidéo ne contient pas la requête cible.',
  vDescNone:'Ajoutez une description de la vidéo.',
  vDescMax:n=>'La description de la vidéo fait '+thousands(n)+' caractères. YouTube en accepte 5 000.',
  vDescShort:n=>'La description de la vidéo est courte ('+pl(n,'caractère','caractères')+'). Décrivez ce que montre la vidéo en deux ou trois phrases.',
  vDescGood:n=>'Bonne longueur de la description de la vidéo : '+pl(n,'caractère','caractères')+'.',
  vDescKpStart:'La requête cible figure dans les 160 premiers caractères de la description de la vidéo.',
  vDescKpLate:'La requête cible figure dans la description de la vidéo, mais pas dans les 160 premiers caractères, ceux qui s’affichent dans les résultats.',
  vDescNoKp:'La description de la vidéo ne contient pas la requête cible.',
  chOk:n=>n+' chapitres trouvés. Google peut les afficher comme « moments clés ».',
  chBad:'Des horodatages de chapitres ont été trouvés, mais il en faut au moins trois, à partir de 0:00, d’au moins 10 secondes chacun.',
  chNone:'Aucun chapitre. Ajoutez des horodatages comme « 0:00 Introduction » sur des lignes séparées pour que Google affiche les moments clés.',
  thNone:'Ajoutez l’URL d’une miniature. Google en a besoin pour afficher la vidéo dans les résultats.',
  thUrl:'La miniature doit être une adresse complète commençant par https://.',
  thError:'Impossible de charger la miniature. Vérifiez que l’adresse est correcte et publique.',
  thLoading:'Chargement de la miniature pour vérifier sa taille.',
  thPlaceholder:'C’est l’image par défaut de YouTube : la vidéo n’a pas de miniature haute résolution. Utilisez hqdefault.jpg ou importez une miniature personnalisée.',
  thGood:(w,h)=>'Bonne taille de miniature : '+w+' × '+h+' px.',
  thOk:(w,h)=>'La miniature fait '+w+' × '+h+' px. À partir de 1280 × 720 px, elle sera plus nette.',
  thSmall:(w,h)=>'Miniature trop petite : '+w+' × '+h+' px. Utilisez au moins 1280 × 720 px.',
  th169:'La miniature est au format 16:9.',
  thRatio:r=>'Le format de la miniature est de '+dec(r,2)+':1. Les résultats vidéo utilisent le 16:9 : elle sera recadrée ou affichée avec des bandes.',
  thHttp:'Utilisez une adresse en https:// pour la miniature.',
  dateNone:'Ajoutez la date de mise en ligne. Google l’exige.',
  dateBad:'Saisissez une date de mise en ligne valide.',
  dateFuture:'La date de mise en ligne est dans le futur.',
  dateOk:d=>'Date de mise en ligne indiquée ('+d+').',
  date:d=>d.split('-').reverse().join('/'),
  durNone:'Ajoutez la durée pour que les résultats puissent l’afficher.',
  durBad:'Écrivez la durée sous la forme 4:35, 1:02:03 ou PT4M35S.',
  durOk:(c,iso)=>'Durée : '+c+' ('+iso+').',
  capOk:'Des sous-titres sont disponibles.',
  capNo:'Les sous-titres ne sont pas indiqués comme disponibles. Ils servent aux personnes sourdes ou malentendantes, et à celles qui regardent sans le son.',
  trNone:'Ajoutez une transcription. Elle rend le contenu parlé de la vidéo indexable et accessible.',
  trShort:n=>'La transcription est courte ('+pl(n,'mot','mots')+'). Incluez tout ce qui est dit.',
  trOk:n=>'Transcription : '+pl(n,'mot','mots')+'.',
  trKp:'La transcription contient la requête cible.',
  trNoKp:'La transcription ne contient pas la requête cible.',
  lenGood:(n,inc)=>'Bonne longueur : '+n+' mots'+(inc?', transcription comprise':'')+'.',
  lenOk:(n,inc)=>'Assez court : '+n+' mots'+(inc?', transcription comprise':'')+'. 300 mots ou plus sont préférables pour le référencement.',
  lenBad:(n,inc)=>'Contenu trop mince : '+pl(n,'mot','mots')+(inc?', transcription comprise':'')+'. Visez au moins 300 mots.',
  bodyVideo:'Ajoutez une courte introduction autour de la vidéo. Le texte de la page aide les moteurs de recherche à la comprendre.',
  bodyNone:'Ajoutez le corps du texte pour vérifier le contenu.',
  firstKp:'La requête cible apparaît dans le premier paragraphe.',
  firstNoKp:'La requête cible n’apparaît pas dans le premier paragraphe.',
  densNone:'La requête cible n’apparaît pas dans le texte.',
  densLow:(d,n)=>'Densité de la requête cible faible : '+dec(d,1)+' % ('+pl(n,'occurrence','occurrences')+'). Visez 0,5 % à 3 %.',
  densGood:(d,n)=>'Bonne densité de la requête cible : '+dec(d,1)+' % ('+pl(n,'occurrence','occurrences')+').',
  densHigh:(d,n)=>'Densité de la requête cible trop élevée : '+dec(d,1)+' % ('+pl(n,'occurrence','occurrences')+'). Cela peut passer pour du bourrage de mots-clés.',
  headKp:'Un intertitre contient la requête cible.',
  headNoKp:'Aucun intertitre ne contient la requête cible.',
  headNone:'Aucun intertitre. Découpez les textes longs avec des intertitres.',
  headOk:n=>pl(n,'intertitre trouvé','intertitres trouvés')+'.',
  longP:n=>n>1?n+' paragraphes dépassent 150 mots.':'1 paragraphe dépasse 150 mots.',
  sentGood:(p,max)=>'Bonne longueur de phrases : '+p+' % des phrases dépassent '+max+' mots.',
  sentOk:(p,max)=>p+' % des phrases dépassent '+max+' mots. Essayez de rester sous 25 %.',
  sentBad:(p,max)=>p+' % des phrases dépassent '+max+' mots. Raccourcissez-en quelques-unes.',
  read:(s,label)=>'Facilité de lecture (Flesch, adaptation de Kandel et Moles) : '+s+' sur 100, '+label+'.',
  readLabel:s=>s>=90?'très facile':s>=80?'facile':s>=70?'assez facile':s>=60?'standard':s>=50?'assez difficile':s>=30?'difficile':'très difficile',
  readAdvice:'Utilisez des phrases et des mots plus courts pour faciliter la lecture.',
  transGood:p=>p+' % des phrases contiennent un mot de transition.',
  transLow:p=>'Seulement '+p+' % des phrases contiennent un mot de transition (cependant, ainsi, en effet…). Visez 30 % ou plus.',
  intNone:hasDomain=>'Aucun lien interne trouvé.'+(hasDomain?'':' Indiquez le domaine du site pour que les liens absolus soient bien classés.'),
  intOk:n=>pl(n,'lien interne','liens internes')+'.',
  outNone:'Aucun lien sortant trouvé.',
  outOk:n=>pl(n,'lien sortant','liens sortants')+'.',
  imgThumb:'Pas d’image mise en avant. Utilisez la miniature de la vidéo comme og:image pour les partages.',
  imgNone:'Ajoutez une image mise en avant. Les réseaux sociaux l’utilisent quand la page est partagée.',
  imgGood:(w,h)=>'Bonne taille : '+w+' × '+h+' px.',
  imgOk:(w,h)=>'Taille acceptable ('+w+' × '+h+' px), mais 1200 × 630 px ou plus s’affiche mieux.',
  imgSmall:(w,h)=>'Trop petite : '+w+' × '+h+' px. Utilisez au moins 1200 × 630 px.',
  imgRatioGood:'Le format est proche de 1,91:1 : l’image sera peu recadrée.',
  imgRatio:r=>'Le format est de '+dec(r,2)+':1. Les cartes sociales utilisent environ 1,91:1 : l’image sera recadrée.',
  imgDimUnknown:'Dimensions de l’image inconnues. Importez le fichier pour vérifier sa taille.',
  imgLoading:'Chargement de l’image pour vérifier sa taille.',
  imgError:'Impossible de charger l’image. Vérifiez que l’adresse est correcte et publique.',
  imgUrlBad:'L’adresse de l’image doit être complète et commencer par https://.',
  sizeGood:s=>'Bon poids de fichier : '+s+'.',
  sizeOk:s=>'Le fichier pèse '+s+'. Sous 300 Ko, il se charge plus vite.',
  sizeBad:s=>'Le fichier pèse '+s+'. Compressez-le sous 1 Mo, idéalement sous 300 Ko.',
  imgFormat:t=>'Format '+t+'. JPEG, PNG ou WebP sont les plus sûrs.',
  altNone:'Ajoutez un texte alternatif à l’image.',
  altLong:n=>'Le texte alternatif est long ('+pl(n,'caractère','caractères')+'). Les lecteurs d’écran gèrent mieux 125 caractères ou moins.',
  altOk:'Texte alternatif présent.',
  altKp:'Le texte alternatif contient la requête cible.',
  altNoKp:'Le texte alternatif ne contient pas la requête cible.',
  kb:n=>n<1024?n+' o':n<1048576?Math.round(n/1024)+' Ko':dec(n/1048576,1)+' Mo',
  tagsNone:'Aucune étiquette. Trois à huit étiquettes pertinentes aident les contenus associés et la recherche interne.',
  tagsFew:n=>'Seulement '+pl(n,'étiquette','étiquettes')+'. Trois à huit, c’est l’idéal.',
  tagsOk:n=>n+' étiquettes.',
  tagsMany:n=>n+' étiquettes. Au-delà de huit, elles perdent de leur valeur.',
  tagsDup:l=>'Étiquettes en double : '+l+'.',
  tagsLong:l=>'Certaines étiquettes sont de longues expressions : '+l+'.',
  tagKp:'Une étiquette correspond à la requête cible.',
  tagNoKp:'Aucune étiquette ne correspond à la requête cible.',
  h1One:'Un seul titre H1.',
  h1None:'Aucun titre H1.',
  h1Many:n=>n+' titres H1. L’usage est d’en avoir un seul.',
  canOk:'L’URL canonique est définie.',
  canNo:'Pas d’URL canonique.',
  ogAll:'Le titre, la description et l’image Open Graph sont définis.',
  ogPart:l=>'Open Graph incomplet : il manque '+l+'.',
  ogNone:'Aucune balise Open Graph.',
  twOk:'La balise de carte Twitter/X est définie.',
  twNo:'Pas de balise twitter:card.',
  langOk:l=>'La langue de la page est déclarée ('+l+').',
  langNo:'Pas d’attribut lang sur l’élément html.',
  hrefOk:n=>pl(n,'alternative hreflang déclarée','alternatives hreflang déclarées')+'.',
  hrefNo:'Aucune alternative hreflang. Ajoutez-en pour relier les versions linguistiques.',
  noindex:'La balise meta robots bloque l’indexation (noindex).',
  vpOk:'La balise viewport est définie.',
  vpNo:'Pas de balise viewport.',
  noAlt:n=>n>1?n+' images du contenu n’ont pas d’attribut alt.':'1 image du contenu n’a pas d’attribut alt.',
  allAlt:'Toutes les images du contenu ont un attribut alt.',
  ldNone:'Aucune donnée structurée VideoObject. Copiez dans la page le JSON-LD affiché sous les vérifications.',
  ldMissing:l=>'Il manque '+l+' dans les données structurées VideoObject.',
  ldOk:'Les données structurées VideoObject ont les propriétés obligatoires.',
  embOk:'La vidéo est intégrée dans la page.',
  embNo:'Aucune intégration YouTube ou Vimeo trouvée dans la source. Elle est peut-être ajoutée par un script.',
  ogvOk:'La balise og:video est définie.',
  ogvNo:'Pas de balise og:video. Certaines plateformes l’utilisent pour lire la vidéo dans la publication.',
  titleHint:(n,w,max)=>pl(n,'caractère','caractères')+', environ '+w+' px sur '+max,
  descHint:n=>pl(n,'caractère','caractères')+' sur 158',
  words:n=>pl(n,'mot','mots'),
  vtitleHint:n=>pl(n,'caractère','caractères')+' sur 100',
  chars:n=>pl(n,'caractère','caractères'),
  dims:(w,h)=>w+' × '+h+' px',
  loading:'Chargement',noImage:'Pas d’image',none:'Aucune',remote:'Distante',remove:'Retirer',
  serpTitle:'Votre titre SEO s’affiche ici',serpDesc:'Votre méta description s’affiche ici.',
  socialRemote:'Image définie dans la source :',socialTitle:'Titre',socialDesc:'Description',
  fetchFirst:'Saisissez d’abord une adresse YouTube ou Vimeo.',
  fetching:p=>'Récupération des informations depuis '+p+'.',
  fieldNames:{vtitle:'titre',vdesc:'description',vdur:'durée',vdate:'date de mise en ligne',vthumb:'miniature'},
  filled:l=>'Champs remplis : '+l+'.',
  nothingFilled:'Aucun champ vide à remplir.',
  ytNote:' YouTube ne fournit ni la description, ni la date, ni la durée sans clé d’API : copiez-les depuis YouTube Studio.',
  fetchFail:'Impossible de récupérer les informations. La vidéo est peut-être privée, ou la requête a été bloquée.',
  ldCopied:'JSON-LD copié.',ldCopyFail:'Échec de la copie. Sélectionnez le code et copiez-le.',
  linkCounts:(i,x)=>pl(i,'interne','internes')+', '+pl(x,'externe','externes'),
  linkInternal:'Lien interne',linkExternal:'Lien externe',
  linkPhInt:dom=>'/actualites/... ou https://'+(dom||'votre-site.fr')+'/...',linkPhExt:'https://example.org/page',
  linkUpdate:'Mettre à jour le lien',linkApply:'Appliquer',
  noteExt:'Cette adresse est sur un autre site : elle comptera comme un lien externe.',
  noteInt:'Cette adresse est sur votre site : elle comptera comme un lien interne.',
  noteHttps:'https:// sera ajouté.',
  noteNoSel:'Aucun texte n’est sélectionné : l’adresse servira de texte du lien.',
  noteDomain:'Indiquez le domaine du site ci-dessus pour que les adresses complètes de votre site soient reconnues.',
  copyOk:'HTML copié.',copyFail:'Échec de la copie. Utilisez la vue HTML pour copier le code.',
  notHtml:'Cela ne ressemble pas au code source d’une page HTML.',
  videoDetected:'Page vidéo détectée. ',
  imported:'Champs remplis à partir de la source. Indiquez la requête cible pour compléter les vérifications.',
  exampleLoaded:'Exemple chargé. Modifiez un champ pour voir les vérifications évoluer.'
};

// French typography: non-breaking space before : ; ! ? % and inside « ». Applied to every message.
const typo=s=>s.replace(/ ([:;!?%»])/g,' $1').replace(/« /g,'« ');
Object.keys(msgs).forEach(k=>{const v=msgs[k];
  if(typeof v==='string')msgs[k]=typo(v);
  else if(typeof v==='function')msgs[k]=(...a)=>{const r=v(...a);return Array.isArray(r)?r.map(typo):typeof r==='string'?typo(r):r};
});

window.SEO_PAGE_CHECK_LANG={
  rules:{
    storageKey:'seo-check-fr-v1',
    // Function words (mots vides): not counted in the keyphrase length and not required in the URL.
    stopwords:['a','à','au','aux','avec','ce','ces','cet','cette','d','dans','de','des','du','en','et','l','la','le','les','leur','leurs',
      'ma','mes','mon','n','ne','nos','notre','ou','où','par','pas','pour','qu','que','qui','sa','se','ses','son','sur','ta','tes','ton',
      'un','une','vos','votre','y','est','sont','chez','sans','sous','vers','entre','plus','très','tout','tous','toute','toutes'],
    typography:true,
    // Flesch reading ease adapted to French by Kandel and Moles (1958), as used by Yoast SEO.
    readability:{base:207,perWord:1.015,perSyllable:73.6},
    transitions:['ainsi','alors','aussi','cependant','certes','donc','d\'abord','tout d\'abord','de plus','en outre','enfin','ensuite','finalement',
      'néanmoins','notamment','par ailleurs','par conséquent','par contre','par exemple','pourtant','puis','toutefois','d\'ailleurs','en effet',
      'en revanche','en fait','en somme','en conclusion','en résumé','bref','c\'est-à-dire','car','puisque','parce que','afin de','afin que',
      'de même','également','premièrement','deuxièmement','troisièmement','d\'une part','d\'autre part','au contraire','malgré','bien que',
      'quoique','tandis que','alors que','grâce à','à cause de','c\'est pourquoi','de sorte que','si bien que','en particulier','surtout',
      'autrement dit','en d\'autres termes','pour conclure','pour commencer','en premier lieu','en second lieu','dans l\'ensemble','de ce fait',
      'en définitive','au final','en bref','ainsi que','de surcroît','par la suite'],
    sentenceMax:20
  },
  msgs,
  examples:{
    article:{kp:'récupération d’eau de pluie',title:'Récupération d’eau de pluie : le guide des petites fermes',domain:'example.org',slug:'guides/recuperation-eau-pluie-petites-fermes',
      desc:'La récupération d’eau de pluie aide les petites fermes à passer les périodes sèches. Voici comment choisir une cuve et garder une eau propre.',
      alt:'Cuve de récupération d’eau de pluie près du toit d’une ferme',img_url:'../docs/example-rainwater.jpg',tags:'récupération d’eau de pluie, stockage de l’eau, agriculture, sécheresse',
      body:'<p>La récupération d’eau de pluie est l’un des moyens les moins chers pour aider une petite ferme face aux pluies irrégulières. En effet, un toit, une gouttière et une cuve suffisent à stocker de l’eau pour plusieurs semaines sèches.</p>\n'+
      '<h2>Combien d’eau pouvez-vous récupérer ?</h2>\n<p>Chaque mètre carré de toit recueille environ un litre d’eau par millimètre de pluie. Ainsi, un toit de 100 mètres carrés peut recueillir près de 60 000 litres par an dans une région qui reçoit 600 mm de pluie. Il faut toutefois déduire les pertes dues à l’évaporation et aux débordements. Le <a href="https://www.fao.org/">site de la FAO</a> donne des données de pluie par région pour faire ce calcul.</p>\n'+
      '<h2>Choisir une cuve pour la récupération d’eau de pluie</h2>\n<p>D’abord, prévoyez une cuve pour la plus longue période sèche, et non pour toute l’année. Les cuves en plastique sont légères et faciles à poser. En revanche, les cuves en ferrociment coûtent moins cher par litre et durent plus longtemps. Elles demandent cependant plus de travail. Consultez notre <a href="/guides/cuves-stockage-eau">guide des cuves de stockage</a> pour les comparer.</p>\n'+
      '<h2>Garder une eau propre</h2>\n<ul>\n  <li>Installez un séparateur de premier flot pour écarter l’eau la plus sale du toit.</li>\n  <li>Couvrez chaque ouverture d’une moustiquaire contre les insectes et les feuilles.</li>\n  <li>Nettoyez les gouttières avant la saison des pluies.</li>\n</ul>\n'+
      '<h2>Entretenir l’installation</h2>\n<p>Une fois par an, videz la cuve et nettoyez le fond. Vérifiez aussi les joints et les raccords, car une petite fuite peut faire perdre beaucoup d’eau en été. De plus, contrôlez le couvercle : il doit rester bien fermé pour éviter les moustiques. Pour l’arrosage, un simple filtre suffit. En revanche, pour l’eau des animaux, demandez conseil à un technicien sur le traitement adapté.</p>\n'+
      '<p>Enfin, la récupération d’eau de pluie fonctionne mieux dans un plan plus large. Par exemple, associez-la au paillage, au goutte-à-goutte et à des cultures qui résistent à la sécheresse. Commencez petit, mesurez ce que vous récupérez la première saison, puis agrandissez votre installation.</p>'},
    video:{type:'video',kp:'big buck bunny',title:'Big Buck Bunny : le film d’animation libre de Blender',domain:'example.org',slug:'films/big-buck-bunny',
      desc:'Regardez Big Buck Bunny, le court métrage d’animation libre de la Blender Foundation : un lapin géant se venge de trois rongeurs en dix minutes.',
      tags:'big buck bunny, animation, film libre, blender',vurl:'https://vimeo.com/1084537',vtitle:'Big Buck Bunny',
      vdesc:'Big Buck Bunny raconte l’histoire d’un lapin géant au cœur plus gros que lui. Un jour de soleil, trois rongeurs le harcèlent. Il leur prépare alors une revanche pleine d’humour.\n\n0:00 Générique d’ouverture\n0:45 Un matin ensoleillé\n2:40 Les rongeurs attaquent\n5:30 Bunny prépare sa revanche\n8:10 Générique de fin',
      vthumb:'https://i.vimeocdn.com/video/20963649-f02817456fc48e7c317ef4c07ba259cd4b40a3649bd8eb50a4418b59ec3f5af5-d_1280x720',vdate:'2008-05-29',vdur:'9:57',vcap:false,
      vtrans:'Le film ne contient aucun dialogue. Cette transcription décrit ce qui se passe à l’écran. Un matin de soleil, un oiseau se réveille dans un arbre de la forêt. Big Buck Bunny, un grand lapin très doux, sort de son terrier et s’étire au soleil. Il admire un papillon et sourit aux fleurs. Trois rongeurs, Frank, Rinky et Gimera, l’observent depuis un arbre. Puis ils lui lancent des fruits. Quand ils tuent un papillon qu’il aimait, Bunny décide de se défendre. Il taille un arc, aiguise des bâtons et pose des pièges dans la forêt. Ensuite, il attend. Un à un, les rongeurs tombent dans ses pièges. Enfin, Bunny fait voler Frank au bout d’un cerf-volant, et le papillon revient.',
      body:'<p>Big Buck Bunny est un court métrage d’animation réalisé par la Blender Foundation avec des logiciels libres. Il est sorti en 2008 sous licence Creative Commons : chacun peut donc le regarder, le partager et le réutiliser.</p>\n'+
      '<p>Regardez le film complet ci-dessus, ou lisez la transcription pour une description de chaque scène. Le <a href="https://peach.blender.org/">site officiel de Big Buck Bunny</a> propose les fichiers de production. Consultez aussi notre <a href="/films">liste de films libres</a>.</p>'}
  }
};
})();
